// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn1v6_qFypuXF2J7re6HRZO4RzDFrweJk',
    appId: '1:200752266284:web:4b30d53b55d1b041ad2589',
    messagingSenderId: '200752266284',
    projectId: 'emregvn-flutter-first',
    authDomain: 'emregvn-flutter-first.firebaseapp.com',
    storageBucket: 'emregvn-flutter-first.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARH7WjoPySRq4oL3Lv91RKMJMU-nsVy8A',
    appId: '1:200752266284:android:1c44fa64a8efbde0ad2589',
    messagingSenderId: '200752266284',
    projectId: 'emregvn-flutter-first',
    storageBucket: 'emregvn-flutter-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkrqCJDzWARn9nWCQxIJ2SiyYTrkay_WU',
    appId: '1:200752266284:ios:cd72f9792cbb5671ad2589',
    messagingSenderId: '200752266284',
    projectId: 'emregvn-flutter-first',
    storageBucket: 'emregvn-flutter-first.appspot.com',
    iosBundleId: 'com.firstproject.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkrqCJDzWARn9nWCQxIJ2SiyYTrkay_WU',
    appId: '1:200752266284:ios:49be53fbe12de847ad2589',
    messagingSenderId: '200752266284',
    projectId: 'emregvn-flutter-first',
    storageBucket: 'emregvn-flutter-first.appspot.com',
    iosBundleId: 'com.firstproject.firstproject.RunnerTests',
  );
}
